"""
archive — Package current session/scene as a recoverable markdown archive.

Creates a timestamped archive package containing:
- Environment snapshot (if available)
- Active reminders state
- Summary of recent activity
- Label for context recovery

Archives are stored in AUTOMATION/archive-packages/
"""

import os
from datetime import datetime, timezone, timedelta

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils import (
    load_config, read_markdown, load_json, write_markdown,
    now_iso, now_local, generate_id, ensure_dir
)


def cmd_archive(args, root):
    """Execute the archive command."""
    config = load_config(root)
    hours = args.hours
    label = args.label

    companion_name = config.get("companion_name", "companion")
    archive_dir = ensure_dir(os.path.join(root, "AUTOMATION", "archive-packages"))

    # Gather scene components
    snapshot = read_markdown(os.path.join(root, "AUTOMATION", "ENVIRONMENT_SNAPSHOT.md"))
    watchlist = read_markdown(os.path.join(root, "WATCHLIST.md"))
    active_projects = read_markdown(os.path.join(root, "ACTIVE_PROJECTS.md"))
    reminders = load_json(
        os.path.join(root, "AUTOMATION", "reminders.json"), default=[]
    )

    # Build archive document
    archive_id = generate_id("arc")
    timestamp = now_local()

    lines = [
        f"# Scene Archive: {label}",
        f"",
        f"- **ID**: {archive_id}",
        f"- **Companion**: {companion_name}",
        f"- **Created**: {timestamp}",
        f"- **Window**: last {hours} hours",
        f"- **Label**: {label}",
        f"",
        f"---",
        f"",
        f"## Environment Snapshot",
        f"",
    ]

    if snapshot:
        # Include abbreviated snapshot
        snap_lines = snapshot.split("\n")[:30]
        lines.extend(snap_lines)
    else:
        lines.append("_(No snapshot available — run `companion sense` first)_")

    lines.extend([
        "",
        "## Active Projects",
        "",
    ])
    if active_projects:
        proj_lines = active_projects.split("\n")[:20]
        lines.extend(proj_lines)
    else:
        lines.append("_(No active projects file)_")

    lines.extend([
        "",
        "## Pending Reminders",
        "",
    ])
    waiting = [r for r in reminders if r.get("status") == "waiting"]
    if waiting:
        for r in waiting[:10]:
            lines.append(f"- [{r.get('priority', '?')}] {r.get('text', '?')}")
    else:
        lines.append("_(No pending reminders)_")

    lines.extend([
        "",
        "---",
        f"*Archive generated by {companion_name} at {now_iso()}*",
    ])

    archive_content = "\n".join(lines)

    # Write archive file
    filename = f"{datetime.now().strftime('%Y%m%d-%H%M%S')}-{label}.md"
    archive_path = os.path.join(archive_dir, filename)
    write_markdown(archive_path, archive_content)

    # Update scene index
    index_path = os.path.join(root, "AUTOMATION", "SCENE_INDEX.md")
    index_entry = f"- [{archive_id}] {timestamp} — {label} — `{filename}`\n"

    if not os.path.isfile(index_path):
        write_markdown(index_path, "# Scene Index\n\n" + index_entry)
    else:
        with open(index_path, "a", encoding="utf-8") as f:
            f.write(index_entry)

    print(f"[archive] Created: {archive_path}")
    print(f"[archive] ID: {archive_id}")
    print(f"[archive] Label: {label}")
    print(f"[archive] Components: snapshot={'yes' if snapshot else 'no'}, "
          f"projects={'yes' if active_projects else 'no'}, "
          f"reminders={len(waiting)}")
